# yaml-language-server: $schema=https://json.schemastore.org/pre-commit-config.json

repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: 3e8a8703264a2f4a69428a0aa4dcb512790b2c8c  # frozen: v6.0.0
    hooks:
      # https://github.com/pre-commit/pre-commit-hooks?tab=readme-ov-file#hooks-available
      - id: check-executables-have-shebangs
      - id: check-merge-conflict
      - id: check-shebang-scripts-are-executable
      - id: check-symlinks
      - id: check-yaml
      - id: end-of-file-fixer
      - id: trailing-whitespace
  - repo: https://github.com/rhysd/actionlint
    rev: 393031adb9afb225ee52ae2ccd7a5af5525e03e8  # frozen: v1.7.11
    hooks:
      - id: actionlint-system
  - repo: https://github.com/scop/pre-commit-shfmt
    rev: e26a818fd47b4f33cefa99035d1265b0849f4b47  # frozen: v3.13.0-1
    hooks:
      - id: shfmt
  - repo: https://github.com/adrienverge/yamllint
    rev: cba56bcde1fdd01c1deb3f945e69764c291a6530  # frozen: v1.38.0
    hooks:
      - id: yamllint
  - repo: local
    hooks:
      - id: shellcheck
        name: shellcheck
        entry: shellcheck
        language: system
        types:
          - shell
      - id: yamlfmt
        name: yamlfmt
        entry: yamlfmt
        language: system
        types:
          - yaml
