name: Post-Release

on:
  release:
    types: [ created ]

permissions:
  contents: write

jobs:
  upload-artifact:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - name: make ci
      run: make ci
    - name: upload artifact
      run: |
        gh release upload "{{ GITHUB_REF }}" ./backup

