name: Semantic PR

on:
  pull_request_target:
    types:
      - opened
      - edited
      - synchronize

permissions:
  pull-requests: read

jobs:
  semantic-pr:
    runs-on: ubuntu-latest
    steps:
      - uses: amannn/action-semantic-pull-request@0723387faaf9b38adef4775cd42cfd5155ed6017
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          validateSingleCommit: true


# after this project gets to a releasable stage, add this workflow in `release.yml`:
#
# name: Release
#
# on:
#   push:
#     branches:
#       - main
#
# permissions:
#   contents: write
#   pull-requests: write
#
# jobs:
#   release-please:
#     runs-on: ubuntu-latest
#     steps:
#       - uses: googleapis/release-please-action@7987652d64b4581673a76e33ad5e98e3dd56832f
#         with:
#           release-type: simple
#
